apiVersion: v1
kind: Service
metadata:
  name: {{ include "dice.fullname" . }}
  labels:
    {{- include "dice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dice
      protocol: TCP
      name: dice
  selector:
    {{- include "dice.selectorLabels" . | nindent 4 }}
